import {families,compatible,createBuild,validateBuild,metrics,suggest,encodeBuild,decodeBuild} from './core.js';
import {readBuilds,saveBuild,deleteBuild,favorites,toggleFavorite} from './storage.js';
const root=document.querySelector('#loadoutRoot'),legacy=document.querySelector('#legacyEquipment');
const en=()=>window.AsteriaxI18n?.isEnglish?.()===true;
const t=(fr,eng)=>en()?eng:fr;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(n,unit='')=>Number.isFinite(n)?n.toLocaleString(en()?'en-GB':'fr-FR',{maximumFractionDigits:1})+unit:'—';
let data,build,tab='builder',selected='',q='',category='',manufacturer='',size='',grade='',sort='name',onlyFav=false,page=0,compared=[],fav=favorites(),dirty=false,notice='',busy=false,ready=false,proposal=null,mobilePane='ship';
const item=id=>data.components.find(i=>i.id===id),ship=()=>data.ships.find(s=>s.id===build.shipId),slot=()=>ship().slots.find(s=>s.id===selected);
const family=type=>families[type]?.[en()?1:0]||type;
const btn=(action,label,cls='',attrs='')=>`<button type="button" class="lb-button ${cls}" data-lb-action="${action}" ${attrs}>${label}</button>`;
const money=i=>i?.offers?.length?fmt(i.offers[0].price,' aUEC'):t('Prix inconnu','Price unknown');
const titleFor=i=>i.type==='WeaponGun'?`${fmt(i.stats.dps)} DPS · ${fmt(i.stats.range,' m')}`:i.type==='Shield'?`${fmt(i.stats.shield)} HP · ${fmt(i.stats.regen,' /s')}`:i.type==='QuantumDrive'?`${fmt(Number.isFinite(i.stats.speed)?i.stats.speed/1e6:null,' Mm/s')} · ${fmt(i.stats.spool,' s')}`:i.type==='PowerPlant'?`${fmt(i.stats.power)} ${t('segments énergie','power segments')}`:i.type==='Cooler'?`${fmt(i.stats.cooling)} ${t('segments refroidissement','cooling segments')}`:i.type==='Missile'?`${fmt(i.stats.missile)} ${t('dégâts','damage')}`:t('Voir les caractéristiques','View specifications');
function say(message){notice=message;const el=root.querySelector('#lbNotice');if(el)el.textContent=notice}
function mark(){dirty=true;proposal=null;build.updatedAt=new Date().toISOString();render()}
function options(values,value){return `<option value="">${t('Tous','All')}</option>`+values.map(v=>`<option value="${esc(v)}" ${String(v)===value?'selected':''}>${esc(v)}</option>`).join('')}
function render(){if(!data)return;root.dataset.pane=mobilePane;window.AsteriaxLoadout.active=tab!=='legacy';legacy.hidden=tab!=='legacy';
 root.innerHTML=`<div class="lb-heading"><div><p class="eyebrow">${t('CONSTRUIRE · ÉQUIPER · EXPLORER','BUILD · EQUIP · EXPLORE')}</p><h2>${t('ÉQUIPEMENT','EQUIPMENT')}</h2><p>${t('Configurateur — prépare ton vaisseau pour chaque situation.','Loadout Builder — prepare your ship for every situation.')}</p></div><span class="lb-version"><i aria-hidden="true"></i> LIVE · ${esc(data.patch.replace('-LIVE.',' · '))}</span></div>
 <nav class="lb-tabs" aria-label="${t('Modes équipement','Equipment modes')}">${[['builder','Builder','Builder'],['catalog','Catalogue','Catalogue'],['compare','Comparateur','Compare'],['saved','Mes builds','My builds'],['guides','Guides','Guides'],['legacy','Catalogue complet','Full catalogue']].map(([key,fr,eng])=>btn('tab',t(fr,eng),tab===key?'is-active':'',`data-tab="${key}" aria-pressed="${tab===key}"`)).join('')}</nav>
 <p id="lbNotice" class="lb-notice" role="status">${esc(notice)}</p>
 ${tab==='builder'?`<nav class="lb-mobile-nav" aria-label="${t('Panneaux du builder','Builder panels')}">${[['ship','Vaisseau','Ship'],['slots','Slots','Slots'],['catalog','Catalogue','Catalogue'],['summary','Résumé','Summary']].map(([key,fr,eng])=>btn('pane',t(fr,eng),mobilePane===key?'is-active':'',`data-pane="${key}" aria-pressed="${mobilePane===key}"`)).join('')}</nav><div class="lb-workspace">${shipPanel()}${slotsPanel()}${catalogPanel(true)}</div>${summaryPanel()}`:tab==='catalog'?catalogPanel(false):tab==='compare'?comparePanel():tab==='saved'?savedPanel():tab==='guides'?guidesPanel():''}
 <p class="lb-source">${t('Données techniques','Technical data')} : <a href="${data.source}/tree/${data.revision}" target="_blank" rel="noopener">StarCitizenWiki / ScDataDumper</a> · ${esc(data.patch)}. ${t('Prix issus du catalogue Asteriax Verse ; ils peuvent provenir d’un autre patch.','Prices from the Asteriax Verse catalogue; they may belong to another patch.')}</p>`;
 root.querySelectorAll('img').forEach(img=>img.addEventListener('error',()=>{img.hidden=true},{once:true}));
 if(tab==='legacy')window.renderItems?.();
}
function shipPanel(){const s=ship();return `<section class="lb-panel lb-ship"><h3>${t('Vaisseau sélectionné','Selected ship')}</h3><label class="lb-label">${t('Choisir un vaisseau','Choose a ship')}<select id="lbShip">${data.ships.map(v=>`<option value="${v.id}" ${s.id===v.id?'selected':''}>${esc(v.name)}</option>`).join('')}</select></label><h4>${esc(s.name)}</h4><p class="lb-tags"><span>${esc(s.manufacturer)}</span><span>${s.slots.length} ${t('slots','slots')}</span></p><div class="lb-ship-art">${s.photo?`<img src="${esc(s.photo)}" alt="${esc(s.name)}" decoding="async" referrerpolicy="no-referrer">`:'<span aria-hidden="true">✧</span>'}</div><dl>${[[t('Longueur','Length'),fmt(s.length,' m')],[t('Largeur','Width'),fmt(s.width,' m')],[t('Hauteur','Height'),fmt(s.height,' m')],[t('Équipage','Crew'),fmt(s.crew)],['SCU',fmt(s.scu)]].map(([k,v])=>`<div><dt>${k}</dt><dd>${v}</dd></div>`).join('')}</dl>${s.catalogId?btn('shipDetail',t('Voir la fiche complète','View ship details')):''}<p class="lb-muted">${t('Configuration d’origine au changement de vaisseau.','Changing ship restores its stock loadout.')}</p></section>`}
function slotsPanel(){const groups=Object.keys(families).filter(type=>ship().slots.some(s=>s.type===type));return `<section class="lb-panel lb-slots"><div class="lb-panel-head"><h3>${t('Emplacements d’équipement','Equipment slots')}</h3>${btn('reset','↺', '',`aria-label="${t('Réinitialiser','Reset')}"`)}</div><div class="lb-slot-scroll">${groups.map(type=>{const rows=ship().slots.filter(s=>s.type===type);return `<details ${rows.some(s=>s.id===selected)?'open':''}><summary><span>${families[type][2]} ${family(type)}</span><span>${rows.length}</span></summary>${rows.map((s,i)=>{const eq=item(build.slots[s.id]);return `<button type="button" data-lb-action="slot" data-id="${esc(s.id)}" class="lb-slot ${s.id===selected?'is-active':''}" aria-pressed="${s.id===selected}"><span class="lb-icon" aria-hidden="true">${families[type][2]}</span><span><small>${family(type)} ${i+1} · S${s.min===s.max?s.max:s.min+'–'+s.max}${!s.editable?' · '+t('Fixe','Fixed'):''}</small><strong>${esc(eq?.name||s.stockName||t('Vide','Empty'))}</strong><small>${eq?titleFor(eq):t('Données non disponibles','Data unavailable')}</small></span><span>›</span></button>`}).join('')}</details>`}).join('')}</div></section>`}
function catalogue(){let rows=data.components.filter(i=>(tab!=='builder'||compatible(slot(),i))&&(!category||i.type===category)&&(!size||String(i.size)===size)&&(!grade||i.grade===grade)&&(!manufacturer||i.manufacturer===manufacturer)&&(!onlyFav||fav.has(i.id))&&(!q||(i.name+' '+i.manufacturer).toLowerCase().includes(q.toLowerCase())));rows.sort((a,b)=>sort==='price'?(a.offers[0]?.price??Infinity)-(b.offers[0]?.price??Infinity):sort==='dps'?(b.stats.dps??-1)-(a.stats.dps??-1):a.name.localeCompare(b.name));return rows}
function catalogueResults(){const rows=catalogue();page=Math.max(0,Math.min(page,Math.ceil(rows.length/18)-1));return `<p class="lb-count">${rows.length} ${t('composants','components')}${tab==='builder'?' · '+t('compatibles avec ce slot','compatible with this slot'):''}</p><div class="lb-items">${rows.slice(page*18,page*18+18).map(i=>`<article class="lb-item"><div class="lb-icon" aria-hidden="true">${families[i.type][2]}</div><div class="lb-item-copy"><strong>${esc(i.name)}</strong><small>${esc(i.manufacturer)} · S${i.size}${i.grade?' · '+t('Grade','Grade')+' '+esc(i.grade):''}</small><small>${titleFor(i)}</small><span class="lb-price">${money(i)}</span><div class="lb-item-actions">${btn('equip',t('Équiper','Equip'),'lb-primary',`data-id="${i.id}" ${!compatible(slot(),i)?'disabled':''}`)}${btn('compareItem',compared.includes(i.id)?'✓':'⇄','',`data-id="${i.id}" aria-label="${t('Comparer','Compare')} ${esc(i.name)}"`)}${btn('favorite',fav.has(i.id)?'★':'☆','',`data-id="${i.id}" aria-pressed="${fav.has(i.id)}" aria-label="${t('Favori','Favorite')} ${esc(i.name)}"`)}${btn('offers',t('Acheter','Buy'),'',`data-id="${i.id}"`)}</div></div></article>`).join('')||`<p class="lb-muted">${t('Aucun composant pour ces critères.','No components match these filters.')}</p>`}</div><div class="lb-pagination">${btn('prev','←','',page===0?'disabled':'')}<span>${page+1} / ${Math.max(1,Math.ceil(rows.length/18))}</span>${btn('next','→','',(page+1)*18>=rows.length?'disabled':'')}</div>`}
function catalogPanel(builder){return `<section class="lb-panel lb-catalog"><h3>${t('Catalogue d’équipement','Equipment catalogue')}</h3>${builder?`<p class="lb-muted">${family(slot()?.type)} · ${t('Sélectionne un slot au centre.','Select a slot in the centre.')}</p>`:''}<label class="lb-label">${t('Recherche','Search')}<input id="lbSearch" type="search" value="${esc(q)}" placeholder="${t('Rechercher un composant…','Search components…')}"></label><div class="lb-filters"><label>${t('Catégorie','Category')}<select id="lbCategory">${options(Object.keys(families),category).replace(/>(WeaponGun|Missile|Shield|QuantumDrive|PowerPlant|Cooler|WeaponMining|TractorBeam)</g,(_,key)=>'>'+family(key)+'<')}</select></label><label>${t('Taille','Size')}<select id="lbSize">${options([...new Set(data.components.map(i=>i.size))].sort((a,b)=>a-b),size)}</select></label><label>${t('Fabricant','Manufacturer')}<select id="lbManufacturer">${options([...new Set(data.components.map(i=>i.manufacturer))].sort(),manufacturer)}</select></label><label>Grade<select id="lbGrade">${options(['A','B','C','D'],grade)}</select></label></div><div class="lb-filter-bottom"><label><input id="lbOnlyFav" type="checkbox" ${onlyFav?'checked':''}> ${t('Favoris','Favorites')}</label><select id="lbSort" aria-label="${t('Trier','Sort')}"><option value="name" ${sort==='name'?'selected':''}>${t('Nom','Name')}</option><option value="price" ${sort==='price'?'selected':''}>${t('Prix croissant','Price ascending')}</option><option value="dps" ${sort==='dps'?'selected':''}>DPS ↓</option></select></div><div id="lbResults">${catalogueResults()}</div></section>`}
function summaryPanel(){const m=metrics(build,data),stats=[['DPS '+t('théorique','theoretical'),fmt(m.dps)],[t('Boucliers nominaux','Nominal shields'),fmt(m.shield,' HP')],[t('Régénération nominale','Nominal regeneration'),fmt(m.regen,' HP/s')],[t('Vitesse quantum max.','Max. quantum speed'),m.speed===null?'—':fmt(m.speed/1e6,' Mm/s')],[t('Préparation quantum','Quantum spool'),fmt(m.spool,' s')],[t('Énergie produite','Power generated'),fmt(m.power)+' seg.'],[t('Refroidissement produit','Cooling generated'),fmt(m.cooling)+' seg.']];return `<div class="lb-bottom"><section class="lb-panel lb-summary-card"><div class="lb-summary-head"><div><h3>${t('Résumé du build','Build summary')}</h3><p class="lb-total">${fmt(m.cost,' aUEC')}</p><small>${m.unknown?t('Total partiel : ','Partial total: ')+m.unknown+' '+t('prix manquants','missing prices'):t('Meilleurs prix référencés','Lowest listed prices')}</small></div>${btn('shopping',t('⌖ Où acheter','⌖ Where to buy'))}</div><dl class="lb-stat-grid">${stats.map(([k,v])=>`<div><dt>${k}</dt><dd>${v}</dd></div>`).join('')}</dl><p class="lb-muted">${t('Valeurs nominales ; ne simule pas les condensateurs, l’équipage, les pertes ni le réseau complet. Hors prix du vaisseau et frais.','Nominal values; capacitors, crew, losses and the full network are not simulated. Excludes ship price and fees.')}</p></section><section class="lb-panel lb-control-card"><h3>${t('Actions et suggestions','Actions and suggestions')}</h3><label class="lb-label">${t('Nom du build','Build name')}<input id="lbBuildName" maxlength="120" value="${esc(build.name)}"></label><div class="lb-quick-actions">${btn('save',t('Sauvegarder','Save'),'lb-primary')}${btn('share',t('Partager','Share'))}${btn('export','Export JSON')}${btn('image',t('Exporter une image','Export image'))}${btn('copySave',t('Dupliquer','Duplicate'))}${btn('reset',t('Réinitialiser','Reset'),'lb-danger')}</div><h4>${t('Optimisations rapides','Quick optimizations')}</h4><div class="lb-suggestion-grid">${[['dps','Meilleur DPS','Best DPS'],['defense','Meilleure défense','Best defense'],['quantum','Quantum rapide','Fast quantum'],['pve','Profil PvE','PvE profile'],['pvp','Profil PvP','PvP profile']].map(([key,fr,eng])=>btn('suggest',t(fr,eng),'',`data-mode="${key}"`)).join('')}</div><p class="lb-muted">${t('Sauvegardé sur cet appareil. Suggestions nominales à vérifier avant application.','Saved on this device. Review nominal suggestions before applying.')}${dirty?' · '+t('Non sauvegardé','Unsaved'):''}</p></section></div>`}
function comparePanel(){return `<section class="lb-panel"><h3>${t('Comparateur — jusqu’à 3 composants','Compare up to 3 components')}</h3><p>${t('Ajoute des composants avec ⇄ depuis le catalogue.','Add components with ⇄ from the catalogue.')}</p><div class="lb-compare">${compared.map(id=>{const i=item(id);return `<article><h4>${esc(i.name)}</h4><p>${family(i.type)} · S${i.size}</p><dl>${Object.entries(i.stats).filter(([,v])=>v!==null).map(([k,v])=>`<div><dt>${esc(statName(k))}</dt><dd>${fmt(v)}</dd></div>`).join('')}</dl><p>${money(i)}</p>${btn('compareItem',t('Retirer','Remove'),'',`data-id="${id}"`)}</article>`}).join('')||`<p class="lb-muted">${t('Aucune sélection.','Nothing selected.')}</p>`}</div></section>`}
function statName(k){return {dps:'DPS',range:t('Portée (m)','Range (m)'),shield:'HP',regen:'HP/s',speed:t('Quantum (m/s)','Quantum (m/s)'),spool:t('Préparation (s)','Spool (s)'),fuel:'SCU/GM',power:t('Énergie (segments)','Power (segments)'),cooling:t('Refroidissement (segments)','Cooling (segments)'),draw:t('Consommation max. (segments)','Max draw (segments)'),missile:t('Dégâts','Damage')}[k]||k}
function savedPanel(){return `<section class="lb-panel"><h3>${t('Mes builds','My builds')}</h3><label class="lb-label">${t('Importer un build JSON','Import a JSON build')}<input id="lbImport" type="file" accept=".json,application/json"></label><div class="lb-saved">${readBuilds().map(b=>`<article><h4>${esc(b.name)}</h4><p>${esc(b.patch)}</p>${btn('load',t('Ouvrir','Open'),'',`data-id="${esc(b.id)}"`)}${btn('delete',t('Supprimer','Delete'),'lb-danger',`data-id="${esc(b.id)}"`)}</article>`).join('')||`<p>${t('Aucun build sauvegardé sur cet appareil.','No builds saved on this device.')}</p>`}</div></section>`}
function guidesPanel(){return `<section class="lb-panel lb-guide"><h3>${t('Construire un loadout fiable','Build a reliable loadout')}</h3><ol><li>${t('Choisis ton vaisseau puis un emplacement. Le catalogue n’affiche que les composants compatibles avec ses règles connues.','Choose your ship and a slot. The catalogue only shows components matching its known rules.')}</li><li>${t('Les supports et racks restent d’origine. Les composants fixes ne sont pas remplaçables.','Mounts and racks remain stock. Fixed components cannot be replaced.')}</li><li>${t('Compare les statistiques nominales et les prix. Un prix inconnu n’est jamais égal à zéro.','Compare nominal statistics and prices. An unknown price never means free.')}</li><li>${t('Sauvegarde plusieurs variantes ; exporte en JSON pour transférer ton build. Un lien de partage contient une copie du build, pas une sauvegarde synchronisée.','Save multiple variants; export JSON to transfer builds. Share links contain a build snapshot, not a synchronized save.')}</li></ol><h4>${t('Comprendre les suggestions','Understanding suggestions')}</h4><p>${t('DPS : dégâts nominaux des armes. Défense : capacité nominale des boucliers. Quantum : vitesse maximale. PvE : DPS, boucliers et économie de carburant quantum. PvP : DPS et boucliers. Ces profils ne simulent pas un combat et ne garantissent pas un optimum global.','DPS: nominal weapon damage. Defense: nominal shield capacity. Quantum: top speed. PvE: DPS, shields and quantum fuel efficiency. PvP: DPS and shields. These profiles do not simulate combat or guarantee a global optimum.')}</p></section>`}
function dialog(title,html){let d=document.querySelector('#lbDialog');d?.remove();d=document.createElement('dialog');d.id='lbDialog';d.className='lb-dialog';d.dataset.i18nSkip='';d.innerHTML=`<div class="lb-dialog-head"><h3>${esc(title)}</h3><button type="button" data-lb-close aria-label="${t('Fermer','Close')}">×</button></div><div>${html}</div>`;document.body.append(d);d.querySelector('[data-lb-close]').onclick=()=>d.close();d.addEventListener('click',e=>{if(e.target===d)d.close()});d.showModal();return d}
function offerHtml(i){return `<h4>${esc(i.name)}</h4>${i.offers.length?`<ul class="lb-offers">${i.offers.map(o=>`<li><span>${esc(o.location)}<small>${esc(o.patch||t('Patch du prix inconnu','Price patch unknown'))}</small></span><strong>${fmt(o.price,' aUEC')}</strong></li>`).join('')}</ul>`:`<p>${t('Aucune offre référencée pour ce composant.','No listed offers for this component.')}</p>`}`}
function download(blob,name){const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
root.addEventListener('input',e=>{if(e.target.id==='lbSearch'){q=e.target.value;page=0;root.querySelector('#lbResults').innerHTML=catalogueResults()}if(e.target.id==='lbBuildName'){build.name=e.target.value;dirty=true}});
root.addEventListener('change',async e=>{try{
 const id=e.target.id;
 if(id==='lbShip'){if(dirty&&!confirm(t('Changer de vaisseau et abandonner les modifications non sauvegardées ?','Change ship and discard unsaved changes?'))){e.target.value=build.shipId;return}build=createBuild(data.ships.find(s=>s.id===e.target.value),data.patch);selected=ship().slots.find(s=>s.editable)?.id||ship().slots[0].id;dirty=false;q=category=manufacturer=size=grade='';page=0;render();return}
 if(id==='lbImport'){const file=e.target.files[0];if(!file)return;if(file.size>60000)throw Error('invalidBuild');const b=validateBuild(JSON.parse(await file.text()),data);if(dirty&&!confirm(t('Remplacer le build non sauvegardé ?','Replace unsaved build?')))return;build=b;selected=ship().slots[0].id;tab='builder';mark();return}
 if(id==='lbCategory')category=e.target.value;if(id==='lbSize')size=e.target.value;if(id==='lbManufacturer')manufacturer=e.target.value;if(id==='lbGrade')grade=e.target.value;if(id==='lbSort')sort=e.target.value;if(id==='lbOnlyFav')onlyFav=e.target.checked;page=0;render();
 }catch{say(t('Import invalide ou stockage indisponible. Le patch et les compatibilités doivent correspondre.','Invalid import or storage unavailable. Patch and compatibility must match.'))}});
root.addEventListener('click',async e=>{const b=e.target.closest('[data-lb-action]');if(!b)return;const action=b.dataset.lbAction,id=b.dataset.id;try{
 if(action==='pane'){mobilePane=b.dataset.pane;render()}
 if(action==='tab'){tab=b.dataset.tab;page=0;render()}
 if(action==='slot'){mobilePane='catalog';selected=id;q=category=manufacturer=size=grade='';page=0;render()}
 if(action==='equip'){const i=item(id);if(!compatible(slot(),i))return;build.slots[selected]=id;mark()}
 if(action==='reset'){if(confirm(t('Restaurer tous les composants d’origine ?','Restore all stock components?'))){const name=build.name,oldId=build.id;build=createBuild(ship(),data.patch);build.name=name;build.id=oldId;mark()}}
 if(action==='favorite'){fav=toggleFavorite(id);render()}
 if(action==='compareItem'){if(compared.includes(id))compared=compared.filter(x=>x!==id);else if(compared.length<3)compared.push(id);else say(t('Trois composants maximum.','Maximum three components.'));render()}
 if(action==='prev'||action==='next'){page+=action==='next'?1:-1;root.querySelector('#lbResults').innerHTML=catalogueResults()}
 if(action==='offers')dialog(t('Où acheter','Where to buy'),offerHtml(item(id)));
 if(action==='shopping'){const counts=new Map();Object.values(build.slots).filter(Boolean).forEach(id=>counts.set(id,(counts.get(id)||0)+1));dialog(t('Liste d’achat','Shopping list'),[...counts].map(([id,n])=>`<p>×${n}</p>${offerHtml(item(id))}`).join(''))}
 if(action==='save'||action==='copySave'){if(action==='copySave')build.id=crypto.randomUUID();saveBuild(validateBuild(build,data));dirty=false;render();say(t('Build sauvegardé sur cet appareil.','Build saved on this device.'))}
 if(action==='load'){const next=validateBuild(readBuilds().find(x=>x.id===id),data);if(dirty&&!confirm(t('Abandonner les modifications non sauvegardées ?','Discard unsaved changes?')))return;build=next;selected=ship().slots[0].id;dirty=false;tab='builder';render()}
 if(action==='delete'&&confirm(t('Supprimer ce build sauvegardé ?','Delete this saved build?'))){deleteBuild(id);render()}
 if(action==='export')download(new Blob([JSON.stringify(build,null,2)],{type:'application/json'}),'asteriax-build.json');
 if(action==='share'){const url=new URL(location.href);url.searchParams.set('loadout',encodeBuild(build));url.hash='equipment';if(url.href.length>16000){say(t('Build trop volumineux pour un lien : utilise Export JSON.','Build too large for a link: use Export JSON.'));return}const d=dialog(t('Partager ce build','Share this build'),`<p>${t('Toute personne possédant ce lien peut lire cette copie.','Anyone with this link can read this snapshot.')}</p><textarea readonly aria-label="${t('Lien de partage','Share link')}">${esc(url.href)}</textarea>`);d.querySelector('textarea').select()}
 if(action==='image'){const canvas=document.createElement('canvas'),m=metrics(build,data);canvas.width=1200;canvas.height=240+Object.keys(build.slots).length*30;const c=canvas.getContext('2d');c.fillStyle='#071018';c.fillRect(0,0,canvas.width,canvas.height);c.fillStyle='#52d9ff';c.font='bold 32px sans-serif';c.fillText(build.name.slice(0,60),40,60);c.font='18px sans-serif';c.fillText(ship().name+' · '+build.patch,40,100);c.fillText('DPS '+fmt(m.dps)+' · '+fmt(m.shield)+' HP · '+fmt(m.cost)+' aUEC'+(m.unknown?' ('+t('partiel','partial')+')':''),40,145);c.fillStyle='#eaf6fb';c.font='16px sans-serif';ship().slots.forEach((s,n)=>c.fillText(family(s.type)+' · '+(item(build.slots[s.id])?.name||s.stockName||'—'),40,205+n*30));canvas.toBlob(blob=>{if(blob)download(blob,'asteriax-build.png')})}
 if(action==='shipDetail')window.openVehicle?.(ship().catalogId);
 if(action==='suggest'){proposal=suggest(build,data,b.dataset.mode);const before=metrics(build,data),after=metrics(proposal,data),changes=ship().slots.filter(s=>build.slots[s.id]!==proposal.slots[s.id]);const d=dialog(t('Proposition — vérifier avant d’appliquer','Proposal — review before applying'),`<p>${changes.length} ${t('changements proposés','proposed changes')} · ${t('coût référencé','listed cost')} ${fmt(before.cost)} → ${fmt(after.cost)} aUEC${after.unknown?' · '+t('prix incomplets','incomplete prices'):''}</p><ul>${changes.map(s=>`<li>${esc(item(build.slots[s.id])?.name||'—')} → ${esc(item(proposal.slots[s.id])?.name||'—')}</li>`).join('')}</ul><p>${t('Optimisation nominale par slot ; disponibilité, énergie globale, pilotage et efficacité réelle non garantis.','Nominal per-slot optimization; availability, global energy, piloting and real effectiveness are not guaranteed.')}</p><button type="button" id="lbApplySuggestion">${t('Appliquer','Apply')}</button>`);d.querySelector('#lbApplySuggestion').onclick=()=>{build=proposal;d.close();mark()}}
 }catch{say(t('Action impossible : vérifie le stockage et la validité du build.','Unable to complete action: check storage and build validity.'))}});
window.AsteriaxLoadout={active:true};
async function start(){if(busy||ready)return;busy=true;root.innerHTML=`<p role="status">${t('Chargement du Loadout Builder…','Loading Loadout Builder…')}</p>`;try{const response=await fetch('/loadout/data/catalog.json');if(!response.ok)throw Error();data=await response.json();build=createBuild(data.ships.find(s=>s.name==='RSI Constellation Andromeda')||data.ships[0],data.patch);const shared=new URL(location.href).searchParams.get('loadout');if(shared){try{build=decodeBuild(shared,data)}catch{notice=t('Lien invalide ou build d’un autre patch. Configuration d’origine affichée.','Invalid link or build from another patch. Showing stock loadout.')}}selected=ship().slots.find(s=>s.type==='WeaponGun'&&s.editable)?.id||ship().slots[0].id;ready=true;render()}catch{root.innerHTML=`<p>${t('Données indisponibles.','Data unavailable.')}</p><button id="lbRetry">${t('Réessayer','Retry')}</button>`;root.querySelector('#lbRetry').onclick=start}finally{busy=false}}
document.addEventListener('asteriax:view-change',e=>{if(e.detail==='equipment')void start()});
document.addEventListener('asteriax:language-change',()=>{if(ready)render()});
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});
if(location.hash==='#equipment')void start();
