import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import data from '../data/changelog.json' with {type:'json'};
import {publish} from '../functions/api/changelog/publish.js';
import {releases,embed,SITE} from '../server/changelog.js';
const sql=new DatabaseSync(':memory:');sql.exec(readFileSync(new URL('../migrations/0002_changelog.sql',import.meta.url),'utf8'));
const db={prepare(query){return {bind(...args){return {async first(){return sql.prepare(query).get(...args)||null},async run(){return sql.prepare(query).run(...args)}}}}}};
const env={AX_DB:db,CHANGELOG_PUBLISH_TOKEN:'x'.repeat(64),DISCORD_CHANGELOG_WEBHOOK:'https://discord.com/api/webhooks/123/test'};
const request=(auth=true)=>new Request(SITE+'/api/changelog/publish',{method:'POST',headers:auth?{Authorization:'Bearer '+env.CHANGELOG_PUBLISH_TOKEN}:{}});
let sends=0;const send=async()=>{sends++;return Response.json({id:'123'})};
assert.equal((await publish(request(false),env,data,send)).status,401);assert.equal(sends,0);
const responses=await Promise.all(Array.from({length:8},()=>publish(request(),env,data,send)));
assert.equal(sends,1);assert.ok(responses.some(r=>r.status===200));
assert.equal((await (await publish(request(),env,data,send)).json()).alreadyPublished,true);assert.equal(sends,1);
const next=structuredClone(data);next.versions[0].version='1.2.0';
assert.equal((await publish(request(),env,next,async()=>{sends++;throw Error('timeout')})).status,502);
assert.equal((await publish(request(),env,next,send)).status,409);assert.equal(sends,2);
const sorted={versions:[{...data.versions[0],version:'1.9.0'},{...data.versions[0],version:'1.10.0'}]};assert.equal(releases(sorted)[0].version,'1.10.0');
assert.throws(()=>releases({versions:[data.versions[0],data.versions[0]]}));
const invalid=structuredClone(data);invalid.versions[0].date='2026-02-30';assert.throws(()=>releases(invalid));
const payload=embed(data.versions[0]);assert.deepEqual(payload.allowed_mentions.parse,[]);assert.ok(payload.embeds[0].fields.some(f=>f.name==='⚙️ Technique'));
console.log('PASS: auth, concurrent duplicate prevention, uncertain delivery blocks retry, sorting, bilingual validation and embed');
