import {RSI_STORE_SNAPSHOT,RSI_STORE_SNAPSHOT_UPDATED_AT} from './ships-snapshot.js';

const OFFICIAL_SHIP_MATRIX='https://robertsspaceindustries.com/ship-matrix/index';
const OFFICIAL_PLEDGE_STORE='https://robertsspaceindustries.com/graphql';
const SHIP_MATRIX='https://api.star-citizen.wiki/api/shipmatrix/vehicles';
const GAME_VEHICLES='https://api.star-citizen.wiki/api/vehicles';
const RSI='https://robertsspaceindustries.com';
const VERIFIED_PIPELINE_STATUS=new Map([
  ['galaxy','active-production'],
  ['kraken','active-production'],
  ['krakenprivateer','long-term-production'],
  ['liberator','active-production']
]);
const PLEDGE_PRICE_OVERRIDES={
  terrapin:{url:'https://robertsspaceindustries.com/en/pledge/ships/terrapin/Terrapin',title:'Terrapin',available:false,price:220,currency:'USD',is_warbond:false,discounted:false,price_kind:'historical'},
  '400i':{url:'https://robertsspaceindustries.com/en/pledge/ships/400i/400i',title:'400i',available:false,price:250,currency:'USD',is_warbond:false,discounted:false,price_kind:'historical'},
  x1force:{url:'https://robertsspaceindustries.com/en/pledge/ships/x1/X1-Force',title:'X1 Force',available:false,price:50,currency:'USD',is_warbond:false,discounted:false,price_kind:'historical'},
  cyclonern:{url:'https://robertsspaceindustries.com/en/pledge/ships/cyclone/Cyclone-RN',title:'Cyclone RN',available:false,price:65,currency:'USD',is_warbond:false,discounted:false,price_kind:'historical'},
  f7ahornetmkii:{url:'https://robertsspaceindustries.com/en/pledge/ships/hornet/F7A-Hornet-Mk-II',title:'F7A Hornet Mk II',available:false,price:175,currency:'USD',is_warbond:false,discounted:false,price_kind:'historical'}
};

function textValue(v,depth=0){if(v===null||v===undefined||depth>4)return'';if(typeof v==='string'||typeof v==='number'||typeof v==='boolean')return String(v).trim();if(Array.isArray(v))return v.map(x=>textValue(x,depth+1)).find(Boolean)||'';if(typeof v==='object'){for(const k of ['name','display_name','label','value','title','code','slug','status','type','size']){const t=textValue(v[k],depth+1);if(t)return t}}return''}
function pledgePriceOf(v,offer){const live=Number(offer?.price);if(Number.isFinite(live)&&live>0)return live;const fallback=Number(v?.msrp);return Number.isFinite(fallback)&&fallback>0?fallback:null}
function firstUrl(v,depth=0){if(v===null||v===undefined||depth>6)return'';if(typeof v==='string'){const s=v.trim();if(/^https?:\/\//i.test(s)||s.startsWith('//'))return s.startsWith('//')?'https:'+s:s;if(/^\/(?:media|i|images|rsi|assets)\//i.test(s))return `${RSI}${s}`;return''}if(Array.isArray(v)){for(const x of v){const u=firstUrl(x,depth+1);if(u)return u}return''}if(typeof v==='object'){for(const k of ['source_url','slideshow_wide','hub_large','post','large','medium','small','thumbnail','image','url','src','images','media']){const u=firstUrl(v[k],depth+1);if(u)return u}for(const x of Object.values(v)){const u=firstUrl(x,depth+1);if(u)return u}}return''}
function normalizeStatus(v){const s=textValue(v).toLowerCase().replace(/_/g,'-').replace(/\s+/g,'-');const aliases={'flightready':'flight-ready','flight-ready':'flight-ready','inconcept':'in-concept','in-concept':'in-concept','concept':'concept','activeproduction':'active-production','active-production':'active-production','longtermproduction':'long-term-production','long-term-production':'long-term-production','hangarready':'hangar-ready','hangar-ready':'hangar-ready'};return aliases[s.replace(/-/g,'')]||aliases[s]||s||'unknown'}
function slugName(v){return textValue(v).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim()}
function storeKey(v){const key=slugName(v).replace(/^(?:origin jumpworks|anvil aerospace|anvil|origin|tumbril land systems|tumbril)\s+/,'').replace(/\s+(?:2|10)\s+year$/,'').replace(/\s+(?:warbond|standalone ship|standalone vehicle)$/,'').replace(/[^a-z0-9]/g,'').replace(/starlifter/g,'');return({'ptvbuggy':'ptv','ursarover':'ursa'}[key]||key)}
// Les anciennes gammes Aurora Mk I et Hornet F7 Mk I restent référencées
// avec leur dernier prix connu, mais ne sont plus proposées comme pledges courants.
function isRetiredPledgeKey(key){const value=String(key||'');return /^auroramki(?!i)/.test(value)||/^f7[a-z0-9]*mki$/.test(value)}
function pipelineStatus(v,rawStatus){if(rawStatus==='flight-ready'||rawStatus==='hangar-ready')return rawStatus;const verified=VERIFIED_PIPELINE_STATUS.get(storeKey(v.name));if(verified)return verified;const note=textValue(v.production_note).toLowerCase();if(/active production|currently being built|being built and tested/.test(note))return'active-production';if(/long term production|waiting for resources to start/.test(note))return'long-term-production';return rawStatus}
async function fetchAll(base){const first=await fetch(`${base}?page%5Bsize%5D=200&sort=name`,{headers:{Accept:'application/json','User-Agent':'AsteriaxVerse/1.2'}});if(!first.ok)throw new Error(`${base} ${first.status}`);const json=await first.json();let data=Array.isArray(json.data)?json.data:[];const pages=Number(json.meta?.last_page||json.meta?.lastPage||1);if(pages>1){const rest=await Promise.all(Array.from({length:pages-1},(_,i)=>fetch(`${base}?page%5Bsize%5D=200&page%5Bnumber%5D=${i+2}&sort=name`,{headers:{Accept:'application/json','User-Agent':'AsteriaxVerse/1.2'}}).then(x=>x.ok?x.json():{data:[]})));rest.forEach(x=>{if(Array.isArray(x.data))data.push(...x.data)})}return data}
async function fetchOfficialMatrix(){const response=await fetch(OFFICIAL_SHIP_MATRIX,{headers:{Accept:'application/json','Accept-Language':'en','X-Requested-With':'XMLHttpRequest','User-Agent':'AsteriaxVerse/1.3'}});if(!response.ok)throw new Error(`RSI Ship Matrix ${response.status}`);const json=await response.json();if(json.success===false||!Array.isArray(json.data))throw new Error('Réponse RSI Ship Matrix invalide');return json.data}
async function fetchOfficialStore(){const query='query AsteriaxPledgeStore($query: SearchQuery) { store(name: "pledge", browse: true) { listing: search(query: $query) { resources { id title url nativePrice { amount discounted discountDescription } stock { unlimited qty level } ... on TySku { isWarbond } } } } }';const limit=200;const response=await fetch(OFFICIAL_PLEDGE_STORE,{method:'POST',headers:{Accept:'application/json','Content-Type':'application/json','Accept-Language':'en','User-Agent':'AsteriaxVerse/1.4'},body:JSON.stringify({operationName:'AsteriaxPledgeStore',variables:{query:{skus:{products:['72']},limit,page:1,sort:{field:'weight',direction:'desc'}}},query})});if(!response.ok)throw new Error(`Boutique RSI ${response.status}`);const json=await response.json();if(Array.isArray(json.errors)&&json.errors.length)throw new Error('Réponse boutique RSI invalide');const products=json.data?.store?.listing?.resources;if(!Array.isArray(products)||products.length>=limit)throw new Error('Réponse boutique RSI incomplète');const index=new Map();for(const product of products){const key=storeKey(product.title);if(!key)continue;const path=textValue(product.url);const url=path?(path.startsWith('http')?path:`${RSI}${path.startsWith('/')?path:'/'+path}`):'';const amount=Number(product.nativePrice?.discounted??product.nativePrice?.amount);const available=product.stock?.unlimited===true||Number(product.stock?.qty)>0;const offer={url,title:textValue(product.title),available,price:Number.isFinite(amount)&&amount>0?amount/100:null,currency:'USD',is_warbond:product.isWarbond===true,discounted:Number(product.nativePrice?.discounted)>0,price_kind:'current'};const current=index.get(key);if(!current||(offer.available&&!current.available)||(offer.available===current.available&&offer.price!==null&&(current.price===null||offer.price<current.price)))index.set(key,offer)}return index}
class VerifiedStoreMap extends Map{set(key,offer){const collector=isRetiredPledgeKey(key);return super.set(key,collector?{...offer,available:false,price_kind:'historical',collector:true}:offer)}}
function snapshotStore(){const store=new VerifiedStoreMap(RSI_STORE_SNAPSHOT.map(([key,offer])=>[key,{...offer}]));for(const [key,offer] of Object.entries(PLEDGE_PRICE_OVERRIDES))store.set(key,offer);return store}
function normalize(v,inGameNames=new Set(),storeIndex=null){const name=textValue(v.name);const manufacturer=textValue(v.manufacturer)||textValue(v.manufacturer_name);const image=firstUrl(v.media)||firstUrl(v.image)||firstUrl(v.images);const rawStatus=normalizeStatus(v.production_status);const inGame=rawStatus==='flight-ready'||rawStatus==='hangar-ready'||inGameNames.has(slugName(name));const storeOffer=storeIndex?.get(storeKey(name));return{rsi_id:textValue(v.id),name,manufacturer,status:inGame?'flight-ready':pipelineStatus(v,rawStatus),status_note:textValue(v.production_note),focus:textValue(v.focus),type:textValue(v.type),size:textValue(v.size),scu:v.cargocapacity??null,crew_min:v.min_crew??null,crew_max:v.max_crew??null,length:v.length??null,beam:v.beam??null,height:v.height??null,mass:v.mass??null,msrp:v.msrp??null,description:textValue(v.description),image,rsi_url:v.url?`${RSI}${String(v.url).startsWith('/')?v.url:'/'+v.url}`:'',store_url:storeOffer?.available?storeOffer.url:'',pledge_available:storeIndex?Boolean(storeOffer?.available):null,pledge_collector:storeOffer?.collector===true,pledge_price:pledgePriceOf(v,storeOffer),pledge_currency:storeOffer?.currency||'',pledge_is_warbond:storeOffer?.is_warbond===true,pledge_discounted:storeOffer?.discounted===true,pledge_price_kind:storeOffer?.price_kind||'',updated:textValue(v.time_modified),in_game:inGame}}

export async function onRequestGet(context){const cache=caches.default;const key=new Request(new URL('/api/ships?catalog=v18',context.request.url).toString());const cached=await cache.match(key);if(cached)return cached;try{let source='RSI Ship Matrix officielle';let warning='';let rows;const [officialSettled,storeSettled]=await Promise.allSettled([fetchOfficialMatrix(),fetchOfficialStore()]);const storeLive=storeSettled.status==='fulfilled';const storeIndex=snapshotStore();if(storeLive)for(const [offerKey,offer] of storeSettled.value){const previous=storeIndex.get(offerKey);if(previous?.price&&!offer?.price)storeIndex.set(offerKey,{...previous,...offer,price:previous.price,price_kind:previous.price_kind||'historical'});else storeIndex.set(offerKey,offer)}else warning=`Boutique RSI en direct indisponible (${String(storeSettled.reason?.message||storeSettled.reason)}) · prix issus du relevé officiel du ${RSI_STORE_SNAPSHOT_UPDATED_AT}`;if(officialSettled.status==='fulfilled'){rows=officialSettled.value}else{const officialError=officialSettled.reason;warning=[String(officialError?.message||officialError),warning].filter(Boolean).join(' · ');const [matrixSettled,gameSettled]=await Promise.allSettled([fetchAll(SHIP_MATRIX),fetchAll(GAME_VEHICLES)]);if(matrixSettled.status!=='fulfilled')throw officialError;const gameData=gameSettled.status==='fulfilled'?gameSettled.value:[];const inGameNames=new Set(gameData.map(v=>slugName(v.name)).filter(Boolean));rows=matrixSettled.value.map(v=>({...v,__inGameNames:inGameNames}));source='Star Citizen Wiki API (secours, RSI indisponible)'}const items=rows.map(v=>normalize(v,v.__inGameNames,storeIndex)).filter(x=>x.name);const response=new Response(JSON.stringify({ok:true,source,official:source==='RSI Ship Matrix officielle',store_checked:Boolean(storeIndex),store_live:storeLive,store_updated_at:RSI_STORE_SNAPSHOT_UPDATED_AT,warning,updatedAt:new Date().toISOString(),items}),{headers:{'content-type':'application/json; charset=utf-8','cache-control':'public, max-age=120, s-maxage=1800, stale-while-revalidate=21600','access-control-allow-origin':'*'}});context.waitUntil(cache.put(key,response.clone()));return response}catch(error){return new Response(JSON.stringify({ok:false,error:String(error?.message||error),items:[]}),{status:502,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}})}}


