(()=>{
const owned=new Set(JSON.parse(localStorage.getItem('ax_hangar_owned')||'[]'));
const wished=new Set(JSON.parse(localStorage.getItem('ax_hangar_wishlist')||'[]'));
let ready=false,hangarMode='owned';
const statusLabel=s=>({"flight-ready":"Flight Ready","in-concept":"Concept","concept":"Concept","active-production":"En production","long-term-production":"Production planifiée","hangar-ready":"Hangar Ready"}[String(s||'').toLowerCase()]||String(s||'Statut inconnu').replaceAll('-',' '));
const statusClass=s=>String(s||'unknown').toLowerCase().replace(/[^a-z0-9]+/g,'-');
const key=v=>String(v.id);
const save=()=>{localStorage.setItem('ax_hangar_owned',JSON.stringify([...owned]));localStorage.setItem('ax_hangar_wishlist',JSON.stringify([...wished]))};
function setHangar(id,mode){id=String(id);if(mode==='owned'){owned.has(id)?owned.delete(id):owned.add(id);wished.delete(id)}else{wished.has(id)?wished.delete(id):wished.add(id);owned.delete(id)}save();renderVehicles();renderHangar();toast(mode==='owned'?(owned.has(id)?'Ajouté à mes vaisseaux':'Retiré de mes vaisseaux'):(wished.has(id)?'Ajouté à la wishlist':'Retiré de la wishlist'))}
function imageOf(v){return imgUrl(v.url_photo||v.catalog_image)}
function availability(v){if(Number(v.price_min)>0)return'Achetable in-game';const s=String(v.production_status||'').toLowerCase();if(s==='flight-ready')return'Non vendu in-game actuellement';return statusLabel(s)}
vehicleCard=function(v){const u=imageOf(v),img=u?`<img loading="lazy" src="${esc(u)}" referrerpolicy="no-referrer" alt="${esc(v.name)}" onerror="this.onerror=null;this.replaceWith(Object.assign(document.createElement('div'),{className:'image-fallback',textContent:'AX'}))">`:`<div class="image-fallback">AX</div>`;const ground=Number(v.is_ground_vehicle)===1;const st=statusLabel(v.production_status||'flight-ready');return `<article class="ship-card" data-vehicle-id="${esc(v.id)}" tabindex="0"><div class="ship-state"><span class="status-badge ${statusClass(v.production_status)}">${esc(st)}</span>${owned.has(key(v))?'<span class="hangar-mark">✓ Possédé</span>':wished.has(key(v))?'<span class="hangar-mark">☆ Wishlist</span>':''}</div><div class="ship-image">${img}</div><div class="card-body"><div class="card-kicker"><button class="text-link manufacturer-link" data-manufacturer="${esc(v.manufacturer||'')}">${esc(v.manufacturer||'Constructeur inconnu')}</button><span>${ground?'Terrestre':'Vaisseau'}</span></div><h3>${esc(v.name)}</h3><div class="card-meta"><div><span>Disponibilité</span><strong>${esc(availability(v))}</strong></div><div><span>${Number(v.price_min)>0?'Meilleur prix':'Statut'}</span><strong class="price">${Number(v.price_min)>0?price(v.price_min):esc(st)}</strong></div><div><span>SCU</span><strong>${esc(v.scu??'—')}</strong></div><div><span>Équipage</span><strong>${esc(v.crew??'—')}</strong></div></div></div></article>`}
const oldRenderVehicles=renderVehicles;
renderVehicles=function(){oldRenderVehicles();}
function offersFor(v){if(!state.db||v.catalog_only)return[];try{return query(`SELECT o.price_buy,${locationExpr('t')} location FROM vehicle_offers o JOIN terminals t ON t.id=o.terminal_id WHERE o.vehicle_id=? AND o.price_buy>0 ORDER BY o.price_buy ASC`,[v.id])}catch{return[]}}
openVehicle=function(id){const detail=state.vehicles.find(v=>String(v.id)===String(id));if(!detail)return;const offers=offersFor(detail),ground=Number(detail.is_ground_vehicle)===1,u=imageOf(detail),st=statusLabel(detail.production_status||'flight-ready');const image=u?`<div class="detail-vehicle-image"><img src="${esc(u)}" alt="${esc(detail.name)}" referrerpolicy="no-referrer" onerror="this.parentElement.remove()"></div>`:'';const fields=[['Statut',st],['Disponibilité',availability(detail)],['Type',ground?'Véhicule terrestre':'Vaisseau'],['Constructeur',detail.manufacturer],['Taille',detail.catalog_size],['SCU',detail.scu],['Équipage',detail.crew],['Rôle',detail.roles],['Longueur',detail.catalog_length?detail.catalog_length+' m':'']].filter(x=>x[1]!==null&&x[1]!==undefined&&String(x[1])!=='');openDetail(`${image}<div class="detail-head"><p class="eyebrow">FICHE ${ground?'VÉHICULE':'VAISSEAU'}</p><div class="detail-title-row"><h2>${esc(detail.name_full||detail.name)}</h2></div><p class="detail-sub"><button class="text-link" data-manufacturer="${esc(detail.manufacturer||'')}">${esc(detail.manufacturer||'')}</button>${detail.roles?' · '+esc(detail.roles):''}</p><div class="hangar-actions"><button class="detail-fav ${owned.has(key(detail))?'active':''}" data-hangar-owned="${esc(detail.id)}">${owned.has(key(detail))?'✓ Possédé':'＋ Ajouter à mes vaisseaux'}</button><button class="detail-fav ${wished.has(key(detail))?'active':''}" data-hangar-wish="${esc(detail.id)}">${wished.has(key(detail))?'★ Wishlist':'☆ Ajouter à la wishlist'}</button></div></div><div class="detail-grid">${fields.map(([k,v])=>`<div class="detail-stat"><span>${esc(k)}</span><strong>${esc(v)}</strong></div>`).join('')}</div>${detail.catalog_description?`<div class="ship-description">${esc(detail.catalog_description)}</div>`:''}${patchImpact(detail)}<h3>Où acheter</h3>${offers.length?`<table class="shops"><thead><tr><th>Lieu</th><th>Prix</th></tr></thead><tbody>${offers.map(o=>`<tr><td>${esc(o.location||'—')}</td><td>${price(o.price_buy)}</td></tr>`).join('')}</tbody></table>`:`<div class="empty">${String(detail.production_status).toLowerCase()==='flight-ready'?'Aucune offre d’achat in-game connue actuellement.':'Ce véhicule n’est pas encore disponible à l’achat in-game.'}</div>`}${detail.rsi_url?`<p class="rsi-source"><a href="${esc(detail.rsi_url)}" target="_blank" rel="noopener">Voir la fiche RSI ↗</a></p>`:''}`);document.querySelector('[data-hangar-owned]')?.addEventListener('click',e=>{setHangar(e.currentTarget.dataset.hangarOwned,'owned');openVehicle(id)});document.querySelector('[data-hangar-wish]')?.addEventListener('click',e=>{setHangar(e.currentTarget.dataset.hangarWish,'wish');openVehicle(id)})}
renderHangar=function(){const vs=state.vehicles.filter(v=>hangarMode==='owned'?owned.has(key(v)):wished.has(key(v)));const its=hangarMode==='items'?state.items.filter(v=>isFav('i',v.id)):[];const list=hangarMode==='items'?its:vs;$('#hangarCount').textContent=`${list.length} élément${list.length>1?'s':''}`;$('#hangarGrid').innerHTML=list.length?(hangarMode==='items'?its.map(itemCard).join(''):vs.map(vehicleCard).join('')):`<div class="empty">${hangarMode==='owned'?'Aucun vaisseau possédé enregistré.':hangarMode==='wishlist'?'Ta wishlist est vide.':'Aucun équipement favori.'}</div>`;bindCards($('#hangarGrid'))}
function bindHangarTabs(){document.querySelectorAll('[data-hangar-level]').forEach(b=>b.addEventListener('click',()=>{hangarMode=b.dataset.hangarLevel;document.querySelectorAll('[data-hangar-level]').forEach(x=>x.classList.toggle('active',x===b));renderHangar()}))}
async function loadCatalog(){try{const r=await fetch('/api/ships',{headers:{Accept:'application/json'}});if(!r.ok)throw 0;const data=await r.json();if(!data.ok||!data.items?.length)throw 0;const byName=new Map(state.vehicles.map(v=>[String(v.name).trim().toLowerCase(),v]));for(const c of data.items){const n=String(c.name).trim().toLowerCase(),v=byName.get(n);if(v){Object.assign(v,{production_status:c.status,catalog_size:c.size,catalog_length:c.length,catalog_description:c.description,catalog_image:c.image||v.url_photo,rsi_url:c.rsi_url,roles:v.roles||c.focus,scu:v.scu??c.scu,crew:v.crew??c.crew_max})}else{const nv={id:`rsi-${c.rsi_id}`,name:c.name,name_full:c.name,manufacturer:c.manufacturer,production_status:c.status,catalog_size:c.size,catalog_length:c.length,catalog_description:c.description,catalog_image:c.image,rsi_url:c.rsi_url,roles:c.focus,scu:c.scu,crew:c.crew_max,is_ground_vehicle:c.size==='vehicle'||c.type==='ground'?1:0,price_min:null,location:'',catalog_only:true};state.vehicles.push(nv);byName.set(n,nv)}}state.vehicles.sort((a,b)=>String(a.name).localeCompare(String(b.name),'fr',{numeric:true}));state.manufacturers=[...new Set([...state.manufacturers.map(x=>x.name),...state.vehicles.map(v=>v.manufacturer).filter(Boolean)])].sort((a,b)=>a.localeCompare(b)).map(name=>({name,n:state.vehicles.filter(v=>v.manufacturer===name).length+state.items.filter(v=>v.manufacturer===name).length}));setOptions($('#vehicleManufacturer'),state.manufacturers.map(x=>x.name),'Tous les constructeurs');$('#statVehicles').textContent=state.vehicles.length;renderVehicles();renderDirectories();ready=true}catch(e){console.warn('Catalogue complet indisponible',e)}}
function wait(){if(state.db){bindHangarTabs();loadCatalog()}else setTimeout(wait,150)}wait();
})();